### ISSUE TITLE
Reduce_obs flag at example command

### ISSUE THREAD

**Issue by kimbring2** [gyh75520/Relational_DRL#1]
Hello, Yumho

Thank you for replicating of DRL paper. 

To run example command of How to Run section, reduce_obs flag should be added.
Without that flag, I encountered a concat dimension mismatching error. 

Sincerely,
From Dohyeong

**Comment by gyh75520** [comment]
Hi,@kimbring2

Thank you for finding the problem
I update my repo
Now, you can run 
```python main.py BoxRandWorld -env_level easy RelationalPolicy -total_timesteps 1e8```

or 
```python main.py BoxRandWorld -env_level easy RelationalPolicy -reduce_obs -total_timesteps 1e8```

Using ```reduce_obs``` can Reduce the size of the input.

If there are any other questions, please let me know :)

**Comment by kimbring2** [comment]
Hi, @gyh75520 

Thank you for updating. I will continue to test :-)

From kimbring2
