### ISSUE TITLE
Loading pretrained model

### ISSUE THREAD

**Issue by kimbring2** [gyh75520/Relational_DRL#2]
Hello, 

I can save a model as pkl file. But, I can not load a that model.
I am trying to implement it myself but can not make it yet.

Can you give me some help how to load a model?

Thank you,
From Dohyeong

**Comment by gyh75520** [comment]
Hi, kimbring2

if you want load a mode you trained, follow these steps

1. Uncomment line 80 and 81  in ```main.py```
```
    if config.save:
        model.save(log_dir + 'model.pkl')
```
2. run the command to train your model, remember to add ```-save```
```python main.py BoxRandWorld -env_level easy RelationalPolicy -total_timesteps 1e8 -save```
and you will see this line
```
--------------------------Create dir:exp_result/BoxRandWorldeasy_A2C_RelationalPolicy/log_0/ Successful!--------------------------
```

3. After the training is completed, ```model.pkl``` can be found in dir:exp_result/BoxRandWorldeasy_A2C_RelationalPolicy/log_0/ 

```
import argparse
import json
import numpy as np
from main import set_model, set_env
from matplotlib import pyplot as plt

def draw(figure_n, img, cmp=None):
    fig = plt.figure(figure_n)
    plt.clf()
    plt.imshow(img, cmp)
    fig.canvas.draw()

def run(log_dir):
    # read from config
    parser = argparse.ArgumentParser()
    config = parser.parse_args()
    with open('{}/config.txt'.format(log_dir), 'r') as f:
        config.__dict__ = json.load(f)

    env = set_env(config, log_dir)
    model = set_model(config, env, log_dir)
    model = model.load(log_dir + '/model.pkl', env=env)

    obs, done = env.reset(), None
    process_n = 0  # i-th process
    while True:
        img = obs[process_n, :, :, :] / 255
        draw(0, img)
        action, _states = model.predict(obs)
        obs, rewards, done, info = env.step(action)
        plt.pause(0.0001)

log_dir = 'exp_result/BoxRandWorldeasy_A2C_RelationalPolicy/log_0'
run(log_dir)
```
Run the file, you can load a mode you trained.
Hope this can help you :)

**Comment by kimbring2** [comment]
Hi, Yumho. 

By using your code, I can load my trained model. 
I am very happy because of sum of reward is around 13. 

Relational Reinforcmenet Learning material was very hard to find. Thus, I can study a lot about it with your code. Thank you again.

Sincerely,
Dohyeong Kim

**Comment by gyh75520** [comment]
I'm so glad I could help you :)
